import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, forkJoin, map, timeout } from 'rxjs';
import { buildApiUrl } from '../config/api.config';
import { STANDARD_API_TIMEOUT_MS } from '../config/api-timeout.config';
import { ApiResponse } from '../models/api-response.model';

export interface MainStageOption { id: string; departmentId: string; name: string; sequenceOrder: number; isCritical: boolean; isActive: boolean; }
export interface SubStageOption { id: string; mainStageId: string; mainStageName?: string | null; factoryId?: string; departmentId: string; factoryName?: string | null; departmentNameAr?: string | null; name: string; code: string; capacity: number; sequenceOrder: number; isActive: boolean; }
export interface SubStagePage { items: SubStageOption[]; totalCount: number; pageNumber: number; pageSize: number; }
interface SubStageApiDto extends Omit<SubStageOption, 'sequenceOrder'> { defaultOrder?: number | null; }
export interface StageDependencyItem { key: string; labelAr: string; count: number; }
export interface StageDependencySummary { stageId: string; activeBlockers: StageDependencyItem[]; historicalDependencies: StageDependencyItem[]; canDisable: boolean; canDelete: boolean; disableMessageAr: string; deleteMessageAr: string; }
export interface FactoryItem { id: string; name: string; code: string; location?: string; isActive: boolean; }
export interface CreateFactoryRequest { name: string; code: string; location?: string | null; isActive: boolean; }
export interface UpdateFactoryRequest { name?: string; location?: string | null; isActive?: boolean; }
export interface ProductionLineOption { id: string; factoryId: string; departmentId?: string | null; departmentCode?: string | null; departmentNameAr?: string | null; name: string; lineCode?: string; sequenceOrder: number; isActive: boolean; }
export interface CreateProductionLineRequest { factoryId: string; departmentId: string; name: string; lineCode?: string | null; sequenceOrder: number; isActive: boolean; }
export interface UpdateProductionLineRequest { name?: string; departmentId?: string; sequenceOrder?: number; isActive?: boolean; }
export interface ProductModelItem { id: string; code: string; name: string; description?: string; isActive: boolean; }
export interface ProductModelDeleteEligibility { modelId: string; canDelete: boolean; messageAr: string; }
export interface CreateProductModelRequest { code: string; name: string; description?: string | null; }
export interface UpdateProductModelRequest { name?: string; description?: string | null; isActive?: boolean; }
export interface ProductModelPage { items: ProductModelItem[]; totalCount: number; pageNumber: number; pageSize: number; }
export type CompensationMode = 'SharedPercentage' | 'FullRatePerWorker' | 'FixedAmount';
export interface ModelStageItem { id: string; productModelId?: string; productionLineId: string; subStageId: string; departmentId: string; subStageCode?: string; subStageName?: string; stageOrder: number; piecePrice: number; standardSeconds?: number | null; compensationMode: CompensationMode; isRequired: boolean; isActive: boolean; }
export interface CopyModelStagesRequest { sourceFactoryId: string; sourceDepartmentId: string; sourceProductionLineId: string; targetModelId: string; targetFactoryId: string; targetDepartmentId: string; targetProductionLineId: string; sourceProductModelStageIds: string[]; previewOnly: boolean; note?: string | null; }
export interface CopyModelStagePlan { sourceProductModelStageId: string; subStageId: string; departmentId: string; productionLineId: string; subStageCode: string; subStageName: string; stageOrder: number; targetStageOrder: number; createsTargetStage: boolean; statusLabel: string; }
export interface CopyModelStageSkip { sourceProductModelStageId: string; subStageId: string; stageCode: string; stageName: string; reasonCode: string; reason: string; }
export interface CopyModelStageFailure { sourceProductModelStageId: string; subStageId: string; stageCode: string; stageName: string; reasonCode: string; reason: string; }
export interface CopyModelStagesSummary { sourceFactoryId: string; sourceDepartmentId: string; sourceProductionLineId: string; sourceProductModelId: string; targetFactoryId: string; targetDepartmentId: string; targetProductionLineId: string; targetProductModelId: string; isPreview: boolean; requestedCount: number; addedCount: number; skippedCount: number; failedCount: number; addedStageIds: string[]; plannedStages: CopyModelStagePlan[]; skippedStages: CopyModelStageSkip[]; failedStages: CopyModelStageFailure[]; validationErrors: string[]; }
export interface DepartmentItem { id?: string; factoryId?: string; code?: string; nameAr?: string; nameEn?: string | null; sequenceOrder?: number; productionLineCount?: number; isActive?: boolean; status?: string; departmentId?: number; name?: string; }
export interface CreateDepartmentRequest { factoryId: string; code: string; nameAr: string; nameEn?: string | null; sequenceOrder: number; isActive: boolean; }
export interface UpdateDepartmentRequest { nameAr?: string; nameEn?: string | null; sequenceOrder?: number; isActive?: boolean; }
export interface OperationalStageFilters { factoryId?: string; departmentId?: string; isActive?: boolean; includeInactive?: boolean; name?: string; code?: string; }
export interface FactoryStructureDeleteEligibilityItem { entityId: string; canDelete: boolean; deleteBlockReason?: string | null; }
export interface FactoryStructureDeleteEligibility { factories: FactoryStructureDeleteEligibilityItem[]; departments: FactoryStructureDeleteEligibilityItem[]; lines: FactoryStructureDeleteEligibilityItem[]; }
export interface CreateOperationalStageRequest { departmentId: string; name: string; capacity: number; }

@Injectable({ providedIn: 'root' })
export class ManufacturingMasterDataApiService {
  constructor(private readonly http: HttpClient) {}
  mainStages(): Observable<MainStageOption[]> { return this.getItems('/api/main-stages'); } subStages(): Observable<SubStageOption[]> { return this.getSubStageItems('/api/stages'); } productionLines(): Observable<ProductionLineOption[]> { return this.getItems('/api/production-lines'); }
  searchSubStages(search = '', page = 1, pageSize = 50, isActive = true, field: 'name' | 'code' = 'name'): Observable<SubStagePage> { return this.get<{ items: SubStageApiDto[]; totalCount: number; pageNumber: number; pageSize: number }>(`/api/stages?isActive=${isActive}&page=${page}&pageSize=${pageSize}&${field}=${encodeURIComponent(search)}`).pipe(map(result => ({ ...result, items: (result.items ?? []).map(item => this.toSubStageOption(item)) }))); }
  searchSubStagesByNameOrCode(search = '', page = 1, pageSize = 50, isActive = true): Observable<SubStagePage> {
    if (!search.trim()) return this.searchSubStages('', page, pageSize, isActive);
    return forkJoin([this.searchSubStages(search, page, pageSize, isActive, 'name'), this.searchSubStages(search, page, pageSize, isActive, 'code')]).pipe(map(([byName, byCode]) => ({
      items: [...byName.items, ...byCode.items].filter((item, index, items) => items.findIndex(candidate => candidate.id === item.id) === index),
      totalCount: Math.max(byName.totalCount, byCode.totalCount), pageNumber: page, pageSize
    })));
  }
  factories(): Observable<FactoryItem[]> { return this.getItems('/api/factories?pageSize=200'); }
  factoryStructureDeleteEligibility(): Observable<FactoryStructureDeleteEligibility> { return this.get('/api/factory-structure/delete-eligibility'); }
  allProductionLines(): Observable<ProductionLineOption[]> { return this.getItems('/api/production-lines?includeInactive=true&pageSize=200'); }
  productionLinesForDepartment(departmentId: string): Observable<ProductionLineOption[]> { return this.getItems(`/api/production-lines?departmentId=${encodeURIComponent(departmentId)}&pageSize=200`); }
  mainStagesForDepartment(departmentId: string): Observable<MainStageOption[]> { return this.getItems(`/api/departments/${departmentId}/main-stages?includeInactive=true&pageSize=200`); }
  subStagesForMainStage(mainStageId: string): Observable<SubStageOption[]> { return this.getSubStageItems(`/api/main-stages/${mainStageId}/sub-stages?includeInactive=true&pageSize=200`); }
  allMainStages(): Observable<MainStageOption[]> { return forkJoin([this.getItems<MainStageOption>('/api/main-stages?isActive=true&pageSize=200'), this.getItems<MainStageOption>('/api/main-stages?isActive=false&pageSize=200')]).pipe(map(([active, inactive]) => [...active, ...inactive])); }
  allSubStages(): Observable<SubStageOption[]> { return this.getSubStageItems('/api/stages?includeInactive=true&pageSize=200'); }
  departments(factoryId?: string, includeInactive?: boolean): Observable<DepartmentItem[]> { if (!factoryId && includeInactive === undefined) return this.getItems('/api/departments'); const query = `${factoryId ? `factoryId=${encodeURIComponent(factoryId)}&` : ''}includeInactive=${includeInactive ?? true}&pageSize=200`; return this.getItems(`/api/departments?${query}`); }
  attendanceDepartments(): Observable<DepartmentItem[]> { return this.getItems('/api/attendance/departments'); }
  createFactory(value: CreateFactoryRequest, correlationId?: string): Observable<FactoryItem> { return this.post('/api/factories', value, correlationId); } updateFactory(id: string, value: UpdateFactoryRequest, correlationId?: string): Observable<FactoryItem> { return this.patch(`/api/factories/${id}`, value, correlationId); } deleteFactory(id: string, correlationId?: string): Observable<void> { return this.deleteVoid(`/api/factories/${id}`, correlationId); }
  createProductionLine(value: CreateProductionLineRequest, correlationId?: string): Observable<ProductionLineOption> { return this.post('/api/production-lines', value, correlationId); } updateProductionLine(id: string, value: UpdateProductionLineRequest, correlationId?: string): Observable<ProductionLineOption> { return this.patch(`/api/production-lines/${id}`, value, correlationId); } deleteProductionLine(id: string, correlationId?: string): Observable<void> { return this.deleteVoid(`/api/production-lines/${id}`, correlationId); }
  createMain(value: unknown, correlationId?: string): Observable<MainStageOption> { return this.post('/api/main-stages', value, correlationId); } updateMain(id: string, value: unknown, correlationId?: string): Observable<MainStageOption> { return this.patch(`/api/main-stages/${id}`, value, correlationId); } deactivateMain(id: string, correlationId?: string): Observable<unknown> { return this.delete(`/api/main-stages/${id}`, correlationId); } setMainActivation(id: string, isActive: boolean, correlationId?: string): Observable<MainStageOption> { return this.patch(`/api/main-stages/${id}`, { isActive }, correlationId); }
  createSub(value: unknown, correlationId?: string): Observable<SubStageOption> { return this.postSub('/api/sub-stages', value, correlationId); } updateSub(id: string, value: unknown, correlationId?: string): Observable<SubStageOption> { return this.patchSub(`/api/sub-stages/${id}`, value, correlationId); } deactivateSub(id: string, correlationId?: string): Observable<unknown> { return this.delete(`/api/sub-stages/${id}`, correlationId); } setSubActivation(id: string, isActive: boolean, correlationId?: string): Observable<SubStageOption> { return this.patchSub(`/api/sub-stages/${id}`, { isActive }, correlationId); }
  createOperationalStage(value: CreateOperationalStageRequest, correlationId?: string): Observable<SubStageOption> { return this.postSub('/api/stages', value, correlationId); } updateOperationalStage(id: string, value: unknown, correlationId?: string): Observable<SubStageOption> { return this.patchSub(`/api/stages/${id}`, value, correlationId); } deactivateOperationalStage(id: string, correlationId?: string): Observable<SubStageOption> { return this.postSub(`/api/stages/${id}/deactivate`, {}, correlationId); } deleteOperationalStage(id: string, correlationId?: string): Observable<unknown> { return this.delete(`/api/stages/${id}`, correlationId); } stageDependencies(id: string): Observable<StageDependencySummary> { return this.get(`/api/stages/${id}/dependencies`); }
  operationalStages(filters: OperationalStageFilters): Observable<SubStageOption[]> { const query = new URLSearchParams(); if (filters.factoryId) query.set('factoryId', filters.factoryId); if (filters.departmentId) query.set('departmentId', filters.departmentId); if (filters.name) query.set('name', filters.name); if (filters.code) query.set('code', filters.code); if (filters.isActive !== undefined) query.set('isActive', String(filters.isActive)); if (filters.includeInactive) query.set('includeInactive', 'true'); query.set('pageSize', '200'); return this.getSubStageItems(`/api/stages?${query.toString()}`); }
  createDepartment(value: CreateDepartmentRequest, correlationId?: string): Observable<DepartmentItem> { return this.post('/api/departments', value, correlationId); } updateDepartment(id: string, value: UpdateDepartmentRequest, correlationId?: string): Observable<DepartmentItem> { return this.patch(`/api/departments/${id}`, value, correlationId); } deleteDepartment(id: string, correlationId?: string): Observable<void> { return this.deleteVoid(`/api/departments/${id}`, correlationId); }
  models(): Observable<ProductModelItem[]> { return this.getItems('/api/product-models?includeInactive=true&pageSize=200'); }
  modelSearchPage(search = '', page = 1, pageSize = 10, status: 'all' | 'active' | 'inactive' = 'all'): Observable<ProductModelPage> { const includeInactive = status === 'all'; const isActive = status !== 'inactive'; return this.get<ProductModelPage>(`/api/product-models?includeInactive=${includeInactive}&isActive=${isActive}&search=${encodeURIComponent(search)}&page=${page}&pageSize=${pageSize}`); }
  modelStages(id: string, productionLineId: string): Observable<ModelStageItem[]> { return this.get(`/api/product-models/${id}/production-lines/${productionLineId}/stages`); }
  createModel(value: CreateProductModelRequest, correlationId?: string): Observable<ProductModelItem> { return this.post('/api/product-models', value, correlationId); } updateModel(id: string, value: UpdateProductModelRequest, correlationId?: string): Observable<ProductModelItem> { return this.patch(`/api/product-models/${id}`, value, correlationId); } setModelActivation(id: string, isActive: boolean, correlationId?: string): Observable<unknown> { return this.patch(`/api/product-models/${id}/activation?isActive=${isActive}`, {}, correlationId); } deleteModel(id: string, correlationId?: string): Observable<void> { return this.deleteVoid(`/api/product-models/${id}`, correlationId); } modelDeleteEligibility(id: string): Observable<ProductModelDeleteEligibility> { return this.get(`/api/product-models/${id}/delete-eligibility`); }
  addModelStage(modelId: string, productionLineId: string, value: unknown, correlationId?: string): Observable<ModelStageItem> { return this.post(`/api/product-models/${modelId}/production-lines/${productionLineId}/stages`, value, correlationId); } updateModelStage(modelId: string, productionLineId: string, stageId: string, value: unknown, correlationId?: string): Observable<ModelStageItem> { return this.patch(`/api/product-models/${modelId}/production-lines/${productionLineId}/stages/${stageId}`, value, correlationId); } deactivateModelStage(modelId: string, productionLineId: string, stageId: string, correlationId?: string): Observable<unknown> { return this.delete(`/api/product-models/${modelId}/production-lines/${productionLineId}/stages/${stageId}`, correlationId); }
  copyModelStages(sourceModelId: string, sourceProductionLineId: string, value: CopyModelStagesRequest, correlationId?: string): Observable<CopyModelStagesSummary> { return this.post(`/api/product-models/${sourceModelId}/production-lines/${sourceProductionLineId}/stages/copy`, value, correlationId); }
  private get<T>(path: string): Observable<T> { return this.http.get<ApiResponse<T>>(buildApiUrl(path)).pipe(timeout(STANDARD_API_TIMEOUT_MS), map(x => this.unwrap(x))); } private getItems<T>(path: string): Observable<T[]> { return this.get<{ items: T[] }>(path).pipe(map(page => page.items ?? [])); } private post<T>(path: string, value: unknown, correlationId?: string): Observable<T> { return this.http.post<ApiResponse<T>>(buildApiUrl(path), value, { headers: this.correlationHeaders(correlationId) }).pipe(timeout(STANDARD_API_TIMEOUT_MS), map(x => this.unwrap(x))); } private patch<T>(path: string, value: unknown, correlationId?: string): Observable<T> { return this.http.patch<ApiResponse<T>>(buildApiUrl(path), value, { headers: this.correlationHeaders(correlationId) }).pipe(timeout(STANDARD_API_TIMEOUT_MS), map(x => this.unwrap(x))); } private delete<T>(path: string, correlationId?: string): Observable<T> { return this.http.delete<ApiResponse<T>>(buildApiUrl(path), { headers: this.correlationHeaders(correlationId) }).pipe(timeout(STANDARD_API_TIMEOUT_MS), map(x => this.unwrap(x))); } private deleteVoid(path: string, correlationId?: string): Observable<void> { return this.http.delete<void>(buildApiUrl(path), { headers: this.correlationHeaders(correlationId) }).pipe(timeout(STANDARD_API_TIMEOUT_MS), map(() => void 0)); }
  private getSubStageItems(path: string): Observable<SubStageOption[]> { return this.getItems<SubStageApiDto>(path).pipe(map(items => items.map(item => this.toSubStageOption(item)))); }
  private postSub(path: string, value: unknown, correlationId?: string): Observable<SubStageOption> { return this.post<SubStageApiDto>(path, value, correlationId).pipe(map(item => this.toSubStageOption(item))); }
  private patchSub(path: string, value: unknown, correlationId?: string): Observable<SubStageOption> { return this.patch<SubStageApiDto>(path, value, correlationId).pipe(map(item => this.toSubStageOption(item))); }
  private correlationHeaders(correlationId?: string): HttpHeaders | undefined { return correlationId ? new HttpHeaders({ 'X-Manufacturing-Realtime-Correlation-Id': correlationId }) : undefined; }
  private toSubStageOption(item: SubStageApiDto): SubStageOption { return { ...item, sequenceOrder: item.defaultOrder ?? 0 }; }
  private unwrap<T>(response: ApiResponse<T>): T { if (!response.success || response.data === null || response.data === undefined) throw new Error(response.error?.message || 'تعذر إتمام العملية.'); return response.data; }
}
