import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, map, timeout } from 'rxjs';
import { buildApiUrl } from '../config/api.config';
import { DAILY_PRODUCTION_OPERATION_TIMEOUT_MS, STANDARD_API_TIMEOUT_MS } from '../config/api-timeout.config';
import { ApiResponse } from '../models/api-response.model';

export type ProductionOrderStatus = 'Draft' | 'Active' | 'Completed' | 'Cancelled';
export const PRODUCTION_RECORD_PREVIEW_ROUTE = '/api/production/records/preview';
export interface ProductionOrder { id: string; orderNumber: string; productModelId: string; productModelCode: string; productionLineId?: string; productionDate: string; plannedQuantity: number; status: ProductionOrderStatus; notes?: string; isImported?: boolean; recordedAtUtc?: string; approvedAtUtc?: string; }
export interface ProductionWorkerAllocation { workerId: string; workerCode: string; workerName: string; percentage?: number; fixedAmount?: number; inputQuantity?: number; equivalentQuantity: number; calculatedEarning: number; notes?: string; manualOverrideReason?: string; }
export interface IntakeIssue { severity: string; code: string; message: string; sourceRow?: number; }
export interface RealDataIntakePreview { idempotencyKey: string; canApply: boolean; parsedStageRows: number; parsedWorkerRows: number; parsedProductionWorkerRows: number; stages: { sourceRow: number; stageCode: string; mainStageName: string; subStageName: string; piecePrice: number; standardSeconds?: number; action: string; issues: IntakeIssue[]; }[]; productStageMappings: { stageCode: string; mainStageName: string; subStageName: string; action: string; issues: IntakeIssue[]; }[]; workers: { sourceRow: number; employeeCode: string; sourceName: string; matchedWorkerCode?: string; currentDepartment?: string; incomingDepartment?: string; currentSalary?: number; incomingSalary?: number; action: string; issues: IntakeIssue[]; }[]; productionDays: { productionDate: string; lineQuantity: number; action: string; issues: IntakeIssue[]; }[]; productionStages: { productionDate: string; sourceRow: number; stageName: string; stageCode?: string; workerAllocationCount: number; action: string; issues: IntakeIssue[]; }[]; missingProductStages: { productionDate: string; stageCode: string; stageName: string; severity: string; message: string; }[]; issues: IntakeIssue[]; }
export interface RealDataIntakeApplyResult { batchId: string; idempotencyKey: string; wasAlreadyApplied: boolean; stagesCreated: number; stagesUpdated: number; workersUpdated: number; productionDaysCreated: number; stageRecordsCreated: number; workerAllocationsCreated: number; openReviewIssues: number; }
export interface ProductionDayReview { productionOrderId: string; productionDate: string; recordedAtUtc: string; status: string; lineQuantity: number; factoryName: string; productionLineName: string; productName: string; stageRecordCount: number; workerAllocationCount: number; issues: { productModelStageId: string; stageCode: string; stageName: string; status: string; message: string; resolutionReason?: string; }[]; allocations: { stageProductionRecordId: string; productModelStageId: string; stageCode: string; stageName: string; workerId: string; workerCode: string; workerName: string; inputQuantity?: number; calculatedEarning: number; manualOverrideReason?: string; }[]; }
export interface StageProductionRecord { id: string; productionOrderId: string; productModelStageId: string; productionDate: string; producedQuantity: number; acceptedQuantity: number; rejectedQuantity: number; status: 'Draft' | 'Approved' | 'Cancelled'; stageCode: string; stageName: string; productModelCode: string; productModelName: string; factoryCode: string; factoryName: string; productionLineCode: string; productionLineName: string; mainStageName: string; piecePrice: number; standardSeconds?: number; compensationMode: string; totalWorkerEarnings: number; concurrencyToken: string; workers: ProductionWorkerAllocation[]; notes?: string; approvedByUserId?: string; approvedAtUtc?: string; approvalCancelledByUserId?: string; approvalCancelledAtUtc?: string; approvalCancellationReason?: string; }
export interface DailyProductionCostReportRow extends StageProductionRecord { orderNumber: string; modelCode: string; stageCost: number; }
export interface ProductModelOption { id: string; code: string; name: string; isActive: boolean; description?: string; }
export interface ProductModelStageOption { id: string; productionLineId: string; subStageId: string; subStageCode?: string; subStageName?: string; stageOrder: number; piecePrice: number; standardSeconds?: number; compensationMode: string; isRequired: boolean; isActive: boolean; }
export interface WorkerOption { id: string; employeeCode: string; fullName: string; employmentStatus?: string; isActive?: boolean; }
export interface ProductStageReadiness { productModelStageId: string; subStageId: string; stageCode: string; stageName: string; stageOrder: number; status: 'Ready' | 'NeedsAssignment' | 'AttendanceUnavailable' | 'CompensationNeedsReview' | 'Incomplete' | string; workerStatusText: string; assignedWorkers: number; eligibleWorkers: number; requiredWorkers?: number | null; hasAuthoritativeRequiredWorkerCount: boolean; attendanceDataAvailable: boolean; isFinancialReviewPending: boolean; hasStagePriceConfiguration: boolean; hasCompensationConfiguration: boolean; }
export interface ProductProductionReadiness { productModelId: string; productModelCode: string; productModelName: string; productionLineId: string; productionDate: string; totalStages: number; readyStages: number; stagesWithoutWorkers: number; stagesNeedingCompensationReview: number; stagesWithoutAttendanceData: number; incompleteStages: number; overallReadinessState: string; readyForWorkflowTest: boolean; readyForProductionEntry: boolean; readyForFinancialApproval: boolean; stages: ProductStageReadiness[]; problemStages: ProductStageReadiness[]; }
export type DailyAttendanceStatus = 'Present' | 'Absent' | 'NoSourceCheckIn' | 'AttendanceUnavailable' | string;
export interface DailyProductionWorker { workerId: string; workerCode: string; workerName: string; isOnActiveService: boolean; effectiveAssignmentType?: string | null; attendanceStatus: DailyAttendanceStatus; hasSourceCheckIn: boolean; isPresent: boolean; requiresAuthorizedOverride: boolean; suggestedPercentage?: number | null; contributionStartsAtUtc?: string | null; contributionEndsAtUtc?: string | null; workerMinutes: number; isProductionReady: boolean; exclusionReason?: string | null; isAssignedWorker?: boolean; isDailyOverride?: boolean; }
export interface DailyProductionStage { productModelStageId: string; subStageId: string; mainStageName: string; stageCode: string; stageName: string; stageOrder: number; piecePrice: number; compensationMode: string; staffingStatus: 'Staffed' | 'NoStaffing' | string; attendanceStatus: 'Ready' | 'AbsentWorker' | 'NoSourceCheckIn' | 'NoStaffing' | string; hasAbsentWorkers: boolean; hasNoSourceCheckInWorkers: boolean; isFinancialReviewPending: boolean; isReady: boolean; workers: DailyProductionWorker[]; }
export interface DailyProductionOperations { factoryId: string; factoryName: string; productionLineId: string; productionLineName: string; productModelId: string; productModelCode: string; productModelName: string; productionDate: string; staffingContextVersion: string; totalStages: number; readyStages: number; stagesWithAbsentWorkers: number; stagesWithNoSourceCheckIn: number; stagesWithoutStaffing: number; stagesRequiringCostReview: number; stages: DailyProductionStage[]; activeWorkers: DailyProductionWorker[]; existingDraft?: DailyProductionDraft | null; }
export interface DailyProductionWorkerInput { workerId: string; percentage?: number | null; fixedAmount?: number | null; notes?: string | null; manualOverrideReason?: string | null; inputQuantity?: number | null; }
export interface DailyProductionStageInput { productModelStageId: string; workers: DailyProductionWorkerInput[]; }
export interface DailyProductionOperationInput { factoryId: string; productionLineId: string; productModelId: string; productionDate: string; lineQuantity: number; clientRequestId: string; notes?: string | null; previewToken?: string | null; stages: DailyProductionStageInput[]; }
export interface DailyProductionStagePreview { productModelStageId: string; stageCode: string; stageName: string; stageQuantity: number; stageCost: number; compensationMode: string; workers: ProductionWorkerAllocation[]; warnings: string[]; }
export interface DailyProductionWorkerTotal { workerId: string; workerCode: string; workerName: string; totalEntitlement: number; }
export interface DailyProductionPreview { productionDate: string; lineQuantity: number; previewToken: string; totalWorkerEntitlements: number; stages: DailyProductionStagePreview[]; workerTotals: DailyProductionWorkerTotal[]; warnings: string[]; }
export interface DailyProductionDraft { productionOrderId: string; orderNumber: string; productionDate: string; recordedAtUtc: string; lineQuantity: number; wasAlreadySaved: boolean; stages: StageProductionRecord[]; }
export interface DailyStageApprovalInput { stageProductionRecordId: string; concurrencyToken: string; }
export interface DailyProductionApproval { productionOrderId: string; orderStatus: string; approvedAtUtc: string; approvedStageCount: number; }
export interface DailyProductionApprovalCancellation { productionOrderId: string; orderStatus: string; cancelledAtUtc: string; cancelledStageCount: number; }

@Injectable({ providedIn: 'root' })
export class ProductionCostRecordingApiService {
  constructor(private readonly http: HttpClient) {}
  listOrders(): Observable<ProductionOrder[]> { return this.get<ProductionOrder[]>('/api/production/orders'); }
  listModels(): Observable<ProductModelOption[]> { return this.getItems<ProductModelOption>('/api/production/lookups/models'); }
  listModelStages(modelId: string, productionLineId: string): Observable<ProductModelStageOption[]> { return this.get<ProductModelStageOption[]>(`/api/production/lookups/models/${modelId}/production-lines/${productionLineId}/stages`); }
  listWorkers(): Observable<WorkerOption[]> { return this.getItems<WorkerOption>('/api/production/lookups/workers'); }
  getProductReadiness(productModelId: string, productionLineId: string, productionDate: string): Observable<ProductProductionReadiness> { return this.get<ProductProductionReadiness>(`/api/production/readiness?productModelId=${encodeURIComponent(productModelId)}&productionLineId=${encodeURIComponent(productionLineId)}&productionDate=${encodeURIComponent(productionDate)}`); }
  loadDailyOperations(factoryId: string, productionLineId: string, productModelId: string, productionDate: string): Observable<DailyProductionOperations> { const query = new URLSearchParams({ factoryId, productionLineId, productModelId, productionDate }); return this.get<DailyProductionOperations>(`/api/production/daily-operations?${query.toString()}`); }
  previewDailyOperations(value: DailyProductionOperationInput): Observable<DailyProductionPreview> { return this.post('/api/production/daily-operations/preview', value, DAILY_PRODUCTION_OPERATION_TIMEOUT_MS); }
  saveDailyDraft(value: DailyProductionOperationInput, correlationId?: string): Observable<DailyProductionDraft> { return this.post('/api/production/daily-operations/drafts', value, DAILY_PRODUCTION_OPERATION_TIMEOUT_MS, correlationId); }
  approveDailyOperation(productionOrderId: string, stageApprovals: DailyStageApprovalInput[], correlationId?: string): Observable<DailyProductionApproval> { return this.post(`/api/production/daily-operations/${encodeURIComponent(productionOrderId)}/approve`, { stageApprovals }, DAILY_PRODUCTION_OPERATION_TIMEOUT_MS, correlationId); }
  cancelDailyOperationApproval(productionOrderId: string, stageApprovals: DailyStageApprovalInput[], reason: string, correlationId?: string): Observable<DailyProductionApprovalCancellation> { return this.post(`/api/production/daily-operations/${encodeURIComponent(productionOrderId)}/cancel-approval`, { stageApprovals, reason }, DAILY_PRODUCTION_OPERATION_TIMEOUT_MS, correlationId); }
  createOrder(value: unknown): Observable<ProductionOrder> { return this.post('/api/production/orders', value); }
  updateOrder(id: string, value: unknown): Observable<ProductionOrder> { return this.http.put<ApiResponse<ProductionOrder>>(buildApiUrl(`/api/production/orders/${id}`), value).pipe(timeout(STANDARD_API_TIMEOUT_MS), map((response) => this.unwrap(response))); }
  transitionOrder(id: string, action: 'activate' | 'complete' | 'cancel'): Observable<ProductionOrder> { return this.post(`/api/production/orders/${id}/${action}`, {}); }
  listRecords(from?: string, to?: string, status?: string): Observable<StageProductionRecord[]> { const query = new URLSearchParams(); if (from) query.set('from', from); if (to) query.set('to', to); if (status) query.set('status', status); const suffix = query.size ? `?${query.toString()}` : ''; return this.get<StageProductionRecord[]>(`/api/production/records${suffix}`); }
  getRecord(id: string): Observable<StageProductionRecord> { return this.get<StageProductionRecord>(`/api/production/records/${id}`); }
  createDraft(value: unknown): Observable<StageProductionRecord> { return this.post('/api/production/records', value); }
  updateDraft(id: string, value: unknown): Observable<StageProductionRecord> { return this.http.put<ApiResponse<StageProductionRecord>>(buildApiUrl(`/api/production/records/${id}`), value).pipe(timeout(STANDARD_API_TIMEOUT_MS), map((response) => this.unwrap(response))); }
  calculatePreview(value: unknown): Observable<StageProductionRecord> { return this.post(PRODUCTION_RECORD_PREVIEW_ROUTE, value); }
  approve(id: string, concurrencyToken: string): Observable<StageProductionRecord> { return this.post(`/api/production/records/${id}/approve`, { concurrencyToken }); }
  cancelProductionApproval(id: string, concurrencyToken: string, reason: string): Observable<StageProductionRecord> { return this.post(`/api/production/records/${id}/cancel-production-approval`, { concurrencyToken, reason }); }
  dailyReport(from: string, to: string): Observable<DailyProductionCostReportRow[]> { return this.get<DailyProductionCostReportRow[]>(`/api/production/reports/daily?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); }
  previewRealDataIntake(form: FormData): Observable<RealDataIntakePreview> { return this.http.post<ApiResponse<RealDataIntakePreview>>(buildApiUrl('/api/production/intake/preview'), form).pipe(timeout(120000), map(response => this.unwrap(response))); }
  applyRealDataIntake(form: FormData): Observable<RealDataIntakeApplyResult> { return this.http.post<ApiResponse<RealDataIntakeApplyResult>>(buildApiUrl('/api/production/intake/apply'), form).pipe(timeout(120000), map(response => this.unwrap(response))); }
  getProductionDayReview(productionOrderId: string): Observable<ProductionDayReview> { return this.get<ProductionDayReview>(`/api/production/intake/days/${productionOrderId}`); }
  markStageNotOperated(productionOrderId: string, productModelStageId: string, reason: string): Observable<ProductionDayReview> { return this.post(`/api/production/intake/days/${productionOrderId}/stages/${productModelStageId}/not-operated`, { reason }); }
  setParticipantOverride(productionOrderId: string, stageProductionRecordId: string, workerId: string, reason: string): Observable<ProductionDayReview> { return this.post(`/api/production/intake/days/${productionOrderId}/records/${stageProductionRecordId}/workers/${workerId}/attendance-override`, { reason }); }
  approveProductionDay(productionOrderId: string): Observable<ProductionDayReview> { return this.post(`/api/production/intake/days/${productionOrderId}/approve`, {}); }
  private get<T>(path: string): Observable<T> { return this.http.get<ApiResponse<T>>(buildApiUrl(path)).pipe(timeout(STANDARD_API_TIMEOUT_MS), map((response) => this.unwrap(response))); }
  private getItems<T>(path: string): Observable<T[]> { return this.get<{ items: T[] }>(path).pipe(map((page) => page.items ?? [])); }
  private post<T>(path: string, body: unknown, requestTimeoutMs = STANDARD_API_TIMEOUT_MS, correlationId?: string): Observable<T> { return this.http.post<ApiResponse<T>>(buildApiUrl(path), body, { headers: this.correlationHeaders(correlationId) }).pipe(timeout(requestTimeoutMs), map((response) => this.unwrap(response))); }
  private correlationHeaders(correlationId?: string): HttpHeaders | undefined { return correlationId ? new HttpHeaders({ 'X-Manufacturing-Realtime-Correlation-Id': correlationId }) : undefined; }
  private unwrap<T>(response: ApiResponse<T>): T { if (!response.success || response.data === undefined || response.data === null) { throw new Error(response.error?.message || 'تعذر إتمام العملية.'); } return response.data; }
}
