// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionLinePlanner.Infrastructure.Data;

#nullable disable

namespace ProductionLinePlanner.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("[Role] IS NOT NULL");

                    b.ToTable("AppRoles", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AssignmentTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FromSubStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAutomatic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RelatedTemporaryAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacementForWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ToSubStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromSubStageId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("StartAtUtc");

                    b.HasIndex("ToSubStageId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("WorkerId", "StartAtUtc");

                    b.ToTable("AssignmentTimelineEntries", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Unassigned");

                    b.Property<DateTime>("AttendanceTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttendanceUserId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BadgeNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SourcePayload")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SourceRawId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "AttendanceTimeUtc");

                    b.ToTable("AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityAfterJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EntityBeforeJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestMeta")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Factories", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.MainStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId", "SequenceOrder")
                        .IsUnique();

                    b.ToTable("MainStages", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RelatedEntityId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LineCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId", "LineCode")
                        .IsUnique()
                        .HasFilter("[LineCode] IS NOT NULL");

                    b.ToTable("ProductionLines", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AppUserId", "IsRevoked", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AppRoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.StageReadinessSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AbsentWorkers")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LateWorkers")
                        .HasColumnType("int");

                    b.Property<int>("PresentWorkers")
                        .HasColumnType("int");

                    b.Property<decimal>("ReadinessPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReadinessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Unknown");

                    b.Property<int>("RequiredWorkers")
                        .HasColumnType("int");

                    b.Property<Guid>("ScopeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("UnassignedWorkers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeEntityId", "CalculatedAtUtc");

                    b.ToTable("StageReadinessSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_StageReadinessSnapshot_AbsentNonNegative", "[AbsentWorkers] >= 0");

                            t.HasCheckConstraint("CK_StageReadinessSnapshot_LateNonNegative", "[LateWorkers] >= 0");

                            t.HasCheckConstraint("CK_StageReadinessSnapshot_PresentNonNegative", "[PresentWorkers] >= 0");

                            t.HasCheckConstraint("CK_StageReadinessSnapshot_RequiredNonNegative", "[RequiredWorkers] >= 0");

                            t.HasCheckConstraint("CK_StageReadinessSnapshot_UnassignedNonNegative", "[UnassignedWorkers] >= 0");
                        });
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.SubStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MainStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MainStageId", "SequenceOrder")
                        .IsUnique();

                    b.ToTable("SubStages", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubStage_Capacity_NonNegative", "[Capacity] >= 0");
                        });
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AppUserId", "PermissionId");

                    b.HasIndex("Effect");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissionOverrides", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendanceUserId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BadgeNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.WorkerDefaultAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("SubStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubStageId");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("WorkerDefaultAssignments", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.WorkerTemporaryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromSubStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("ReplacementForWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ToSubStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ToSubStageId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("FromSubStageId", "ToSubStageId");

                    b.ToTable("WorkerTemporaryAssignments", (string)null);
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.HasIndex("AppUserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AssignmentTimelineEntry", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.SubStage", "FromSubStage")
                        .WithMany()
                        .HasForeignKey("FromSubStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.SubStage", "ToSubStage")
                        .WithMany()
                        .HasForeignKey("ToSubStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProductionLinePlanner.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromSubStage");

                    b.Navigation("PerformedByUser");

                    b.Navigation("ToSubStage");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.MainStage", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.ProductionLine", "ProductionLine")
                        .WithMany("MainStages")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RecipientUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.ProductionLine", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.Factory", "Factory")
                        .WithMany("ProductionLines")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppRole", "AppRole")
                        .WithMany("Permissions")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.SubStage", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.MainStage", "MainStage")
                        .WithMany("SubStages")
                        .HasForeignKey("MainStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainStage");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", "AppUser")
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissionOverrides")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.WorkerDefaultAssignment", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.SubStage", "SubStage")
                        .WithMany("DefaultAssignments")
                        .HasForeignKey("SubStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.Worker", "Worker")
                        .WithMany("DefaultAssignmentHistory")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubStage");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.WorkerTemporaryAssignment", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.SubStage", "FromSubStage")
                        .WithMany()
                        .HasForeignKey("FromSubStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.SubStage", "ToSubStage")
                        .WithMany()
                        .HasForeignKey("ToSubStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.Worker", "Worker")
                        .WithMany("TemporaryAssignments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromSubStage");

                    b.Navigation("ToSubStage");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionLinePlanner.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("PermissionOverrides");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Factory", b =>
                {
                    b.Navigation("ProductionLines");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.MainStage", b =>
                {
                    b.Navigation("SubStages");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissionOverrides");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.ProductionLine", b =>
                {
                    b.Navigation("MainStages");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.SubStage", b =>
                {
                    b.Navigation("DefaultAssignments");
                });

            modelBuilder.Entity("ProductionLinePlanner.Domain.Entities.Worker", b =>
                {
                    b.Navigation("DefaultAssignmentHistory");

                    b.Navigation("TemporaryAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
