import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { PermissionService } from '../../core/services/permission.service';
import { ProductionCostRecordingApiService, ProductionOrder, StageProductionRecord, DailyProductionCostReportRow, ProductModelOption, ProductModelStageOption, WorkerOption } from '../../core/services/production-cost-recording-api.service';

@Component({ selector: 'app-production-cost-recording-page', templateUrl: './production-cost-recording-page.component.html', styleUrls: ['./production-cost-recording-page.component.scss'] })
export class ProductionCostRecordingPageComponent implements OnInit {
  orders: ProductionOrder[] = []; records: StageProductionRecord[] = []; report: DailyProductionCostReportRow[] = []; models: ProductModelOption[] = []; modelStages: ProductModelStageOption[] = []; workersList: WorkerOption[] = [];
  loading = true; saving = false; error = ''; preview: StageProductionRecord | null = null; orderSearch = ''; orderStatusFilter = ''; editingOrderId = ''; editingRecordId = ''; recordOrderFilter = ''; recordStatusFilter = ''; recordDateFilter = '';
  readonly today = new Date().toISOString().slice(0, 10);
  readonly orderForm = this.fb.group({ orderNumber: ['', Validators.required], productModelId: ['', Validators.required], productionDate: [this.today, Validators.required], plannedQuantity: [null as number | null, [Validators.required, Validators.min(0.001)]], notes: [''] });
  readonly recordForm = this.fb.group({ productionOrderId: ['', Validators.required], productModelStageId: ['', Validators.required], productionDate: [this.today, Validators.required], producedQuantity: [null as number | null, [Validators.required, Validators.min(0)]], acceptedQuantity: [null as number | null, [Validators.required, Validators.min(0)]], rejectedQuantity: [0, [Validators.required, Validators.min(0)]], clientRequestId: [''], concurrencyToken: [''], notes: [''], workers: this.fb.array([]) });

  constructor(private readonly fb: FormBuilder, private readonly api: ProductionCostRecordingApiService, private readonly permissions: PermissionService) {}
  ngOnInit(): void { this.reload(); this.api.listModels().subscribe({ next: x => this.models = x }); this.api.listWorkers().subscribe({ next: x => this.workersList = x.filter(worker => worker.employmentStatus !== 'LeftEmployment') }); }
  get workers(): FormArray { return this.recordForm.controls.workers; }
  get canRecord(): boolean { return this.permissions.hasPermission('production.record'); }
  get canApprove(): boolean { return this.permissions.hasPermission('production.approve'); }
  get isRecordReadOnly(): boolean { return !!this.editingRecordId && this.recordForm.disabled; }
  addWorker(): void { if (!this.isRecordReadOnly) this.workers.push(this.fb.group({ workerId: ['', Validators.required], percentage: [null], fixedAmount: [null], notes: [''] })); }
  removeWorker(index: number): void { if (!this.isRecordReadOnly) this.workers.removeAt(index); }
  reload(): void { this.loading = true; this.error = ''; this.api.listOrders().pipe(finalize(() => this.loading = false)).subscribe({ next: orders => { this.orders = orders; this.loadRecords(); }, error: error => this.handleError(error, 'تعذر تحميل أوامر الإنتاج.') }); }
  loadRecords(): void { this.api.listRecords().subscribe({ next: records => this.records = records, error: error => this.handleError(error, 'تعذر تحميل سجلات الإنتاج.') }); this.api.dailyReport(this.today, this.today).subscribe({ next: report => this.report = report, error: error => this.handleError(error, 'تعذر تحميل التقرير.') }); }
  filteredOrders(): ProductionOrder[] { const needle = this.orderSearch.trim().toLowerCase(); return this.orders.filter(order => (!this.orderStatusFilter || order.status === this.orderStatusFilter) && (!needle || order.orderNumber.toLowerCase().includes(needle) || order.productModelCode.toLowerCase().includes(needle))); }
  filteredRecords(): StageProductionRecord[] { return this.records.filter(record => (!this.recordOrderFilter || record.productionOrderId === this.recordOrderFilter) && (!this.recordStatusFilter || record.status === this.recordStatusFilter) && (!this.recordDateFilter || record.productionDate === this.recordDateFilter)); }
  orderNumber(record: StageProductionRecord): string { return this.orders.find(order => order.id === record.productionOrderId)?.orderNumber ?? '-'; }
  loadOrderStages(keepStage = false): void { const order = this.orders.find(item => item.id === this.recordForm.controls.productionOrderId.value); if (!keepStage) this.recordForm.controls.productModelStageId.setValue(''); this.modelStages = []; if (order) this.api.listModelStages(order.productModelId).subscribe({ next: stages => this.modelStages = stages.filter(stage => stage.isActive), error: error => this.handleError(error, 'تعذر تحميل مراحل الموديل.') }); }
  selectedStage(): ProductModelStageOption | undefined { return this.modelStages.find(stage => stage.id === this.recordForm.controls.productModelStageId.value); }
  canSelectWorker(workerId: string, index: number): boolean { return !this.workers.controls.some((control, current) => current !== index && control.get('workerId')?.value === workerId); }
  createOrder(): void { if (!this.orderForm.valid || !this.canRecord) { this.orderForm.markAllAsTouched(); return; } this.saving = true; const request = this.editingOrderId ? this.api.updateOrder(this.editingOrderId, this.orderForm.getRawValue()) : this.api.createOrder(this.orderForm.getRawValue()); request.pipe(finalize(() => this.saving = false)).subscribe({ next: () => { this.editingOrderId = ''; this.orderForm.reset({ productionDate: this.today }); this.reload(); }, error: error => this.handleError(error, 'تعذر حفظ الأمر.') }); }
  activate(order: ProductionOrder): void { this.saving = true; this.api.transitionOrder(order.id, 'activate').pipe(finalize(() => this.saving = false)).subscribe({ next: () => this.reload(), error: error => this.handleError(error, 'تعذر تفعيل الأمر.') }); }
  editOrder(order: ProductionOrder): void { if (order.status !== 'Draft' || !this.canRecord) return; this.editingOrderId = order.id; this.orderForm.reset({ orderNumber: order.orderNumber, productModelId: order.productModelId, productionDate: order.productionDate, plannedQuantity: order.plannedQuantity, notes: order.notes ?? '' }); }
  transitionOrder(order: ProductionOrder, action: 'complete' | 'cancel'): void { if (!confirm(action === 'complete' ? 'إكمال أمر الإنتاج؟' : 'إلغاء أمر الإنتاج؟')) return; this.saving = true; this.api.transitionOrder(order.id, action).pipe(finalize(() => this.saving = false)).subscribe({ next: () => this.reload(), error: error => this.handleError(error, 'تعذر تغيير حالة الأمر.') }); }
  newRecord(): void { this.editingRecordId = ''; this.preview = null; this.recordForm.enable(); this.workers.clear(); this.recordForm.reset({ productionDate: this.today, rejectedQuantity: 0, clientRequestId: this.newClientRequestId(), concurrencyToken: '' }); this.modelStages = []; }
  openRecord(record: StageProductionRecord): void { this.saving = true; this.api.getRecord(record.id).pipe(finalize(() => this.saving = false)).subscribe({ next: loaded => { this.editingRecordId = loaded.id; this.preview = loaded; this.recordForm.enable(); this.workers.clear(); this.recordForm.reset({ productionOrderId: loaded.productionOrderId, productModelStageId: loaded.productModelStageId, productionDate: loaded.productionDate, producedQuantity: loaded.producedQuantity, acceptedQuantity: loaded.acceptedQuantity, rejectedQuantity: loaded.rejectedQuantity, clientRequestId: '', concurrencyToken: loaded.concurrencyToken, notes: loaded.notes ?? '' }); loaded.workers.forEach(worker => this.workers.push(this.fb.group({ workerId: [worker.workerId, Validators.required], percentage: [worker.percentage ?? null], fixedAmount: [worker.fixedAmount ?? null], notes: [worker.notes ?? ''] })));
      this.loadOrderStages(true); if (loaded.status !== 'Draft') this.recordForm.disable(); }, error: error => this.handleError(error, 'تعذر فتح سجل الإنتاج.') }); }
  saveDraft(): void { if (this.saving || !this.canRecord || this.isRecordReadOnly || this.recordForm.invalid || this.workers.length === 0 || !this.hasValidQuantities()) { this.recordForm.markAllAsTouched(); this.error = 'تحقق من الكميات وأضف عاملًا واحدًا على الأقل.'; return; } this.saving = true; if (!this.editingRecordId && !this.recordForm.controls.clientRequestId.value) this.recordForm.controls.clientRequestId.setValue(this.newClientRequestId()); const value = this.recordForm.getRawValue(); const request = this.editingRecordId ? this.api.updateDraft(this.editingRecordId, value) : this.api.createDraft(value); request.pipe(finalize(() => this.saving = false)).subscribe({ next: record => { this.applyRecord(record); this.editingRecordId = record.id; this.preview = record; this.recordForm.controls.concurrencyToken.setValue(record.concurrencyToken); this.loadRecords(); }, error: error => this.handleError(error, 'تعذر حفظ المسودة.') }); }
  calculatePreview(): void { if (this.saving || this.recordForm.invalid || this.workers.length === 0 || !this.hasValidQuantities()) { this.error = 'أدخل الكميات والعمال بصورة صحيحة أولًا.'; return; } this.saving = true; this.api.calculatePreview(this.recordForm.getRawValue()).pipe(finalize(() => this.saving = false)).subscribe({ next: preview => this.preview = preview, error: error => this.handleError(error, 'تعذر حساب المعاينة.') }); }
  approve(record: StageProductionRecord): void { if (this.saving || !this.canApprove || record.status !== 'Draft' || !confirm('سيتم تثبيت Snapshot والحسابات. هل تريد الاعتماد؟')) return; this.saving = true; this.api.approve(record.id, record.concurrencyToken).pipe(finalize(() => this.saving = false)).subscribe({ next: updated => { this.applyRecord(updated); this.preview = updated; this.loadRecords(); if (this.editingRecordId === updated.id) this.openRecord(updated); }, error: error => this.handleError(error, 'تعذر اعتماد السجل.') }); }
  cancel(record: StageProductionRecord): void { if (this.saving || !this.canApprove || record.status !== 'Approved' || !confirm('سيتم إلغاء السجل المعتمد واستبعاده من التقرير. هل تريد المتابعة؟')) return; this.saving = true; this.api.cancel(record.id, record.concurrencyToken).pipe(finalize(() => this.saving = false)).subscribe({ next: updated => { this.applyRecord(updated); this.preview = updated; this.loadRecords(); if (this.editingRecordId === updated.id) this.openRecord(updated); }, error: error => this.handleError(error, 'تعذر إلغاء السجل.') }); }
  hasValidQuantities(): boolean { const v = this.recordForm.getRawValue(); return Number(v.acceptedQuantity) + Number(v.rejectedQuantity) <= Number(v.producedQuantity); }
  trackById(_: number, item: { id: string }): string { return item.id; }
  private applyRecord(record: StageProductionRecord): void { this.records = [record, ...this.records.filter(item => item.id !== record.id)]; }
  private newClientRequestId(): string { return globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; }
  private handleError(error: { status?: number; message?: string }, fallback: string): void { this.error = error.status === 409 ? 'تم تعديل السجل بواسطة مستخدم آخر. حدّث البيانات وحاول مرة أخرى.' : (error.message || fallback); }
}
